//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CacheClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.hujao.com/", ConfigurationName="ServiceReference1.ICacheWCF", CallbackContract=typeof(CacheClient.ServiceReference1.ICacheWCFCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ICacheWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.hujao.com/ICacheWCF/GetUserData", ReplyAction="http://www.hujao.com/ICacheWCF/GetUserDataResponse")]
        CacheBusiness.Model.UserInfo[] GetUserData();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.hujao.com/ICacheWCF/AddUser")]
        void AddUser(CacheBusiness.Model.UserInfo u);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.hujao.com/ICacheWCF/DeleteUser")]
        void DeleteUser(CacheBusiness.Model.UserInfo u);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.hujao.com/ICacheWCF/ModifyUser")]
        void ModifyUser(CacheBusiness.Model.UserInfo u);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICacheWCFCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.hujao.com/ICacheWCF/CacheTimeOut")]
        void CacheTimeOut(string TypeName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICacheWCFChannel : CacheClient.ServiceReference1.ICacheWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CacheWCFClient : System.ServiceModel.DuplexClientBase<CacheClient.ServiceReference1.ICacheWCF>, CacheClient.ServiceReference1.ICacheWCF {
        
        public CacheWCFClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public CacheWCFClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public CacheWCFClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CacheWCFClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CacheWCFClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public CacheBusiness.Model.UserInfo[] GetUserData() {
            return base.Channel.GetUserData();
        }
        
        public void AddUser(CacheBusiness.Model.UserInfo u) {
            base.Channel.AddUser(u);
        }
        
        public void DeleteUser(CacheBusiness.Model.UserInfo u) {
            base.Channel.DeleteUser(u);
        }
        
        public void ModifyUser(CacheBusiness.Model.UserInfo u) {
            base.Channel.ModifyUser(u);
        }
    }
}
