//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 --查询用户表对象信息
        ///select  Tab.Name as tablename,
        ///        Col.Name  as colname ,Type.name as typename,Col.max_length as length,
        ///        pk.is_primary_key as is_primary_key,
        ///        Col.is_identity as is_identity,
        ///        identity_columns.seed_value as seed_value,
        ///        identity_columns.increment_value as increment_value,
        ///        Col.is_nullable  AS is_nullable,
        ///        Def.text as defaulttext,
        ///        Col.is_computed as is_computed ,
        ///        computed_columns.definition as definition,
        ///        Col_Desc. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string cols {
            get {
                return ResourceManager.GetString("cols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --查询外键约束
        ///select FK_Name ,Parent_Tab_Name ,delete_referential_action,update_referential_action,[FK_Col]=stuff
        ///(
        ///    (select &apos;,&apos;+[Parent_Col_Name]
        ///		from 
        ///		(
        ///        select    FK.name as FK_Name,Parent_Tab.Name as Parent_Tab_Name,Parent_Col.Name as Parent_Col_Name,
        ///                Referenced_Tab.Name as Referenced_Tab_Name,Referenced_Col.Name as Referenced_Col_Name,FK.delete_referential_action,FK.update_referential_action
        ///        from sys.foreign_keys FK
        ///        inner join sys.foreign_key_columns Co [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string fks {
            get {
                return ResourceManager.GetString("fks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select name FuncName,* from sys.objects where type=&apos;fn&apos;
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string funcs {
            get {
                return ResourceManager.GetString("funcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --查询所有索引
        ///select    indexs.Tab_Name  as Tab_Name,indexs.Index_Name as Index_Name ,indexs.[Co_Names] as Co_Names,
        ///        Ind_Attribute.is_primary_key as is_primary_key,Ind_Attribute.is_unique AS is_unique,
        ///        Ind_Attribute.is_disabled AS is_disabled
        /// from (
        ///    select Tab_Name,Index_Name, [Co_Names]=stuff((select &apos;,&apos;+[Co_Name] from 
        ///    (    select tab.Name as Tab_Name,ind.Name as Index_Name,Col.Name as Co_Name from sys.indexes ind 
        ///        inner join sys.tables tab on ind.Object_id = tab.object_ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string indexs {
            get {
                return ResourceManager.GetString("indexs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --查询所有存储过程
        ///select name as ProcName from sys.procedures
        ///--select Pr_Name  as ProcName, Para=stuff((select &apos;,&apos;+[Parameter] 
        ///    --from (
        ///        --select Pr.Name as Pr_Name,parameter.name +&apos; &apos; +Type.Name + &apos; (&apos;+convert(varchar(32),parameter.max_length)+&apos;)&apos; as Parameter
        ///        --from sys.procedures Pr left join 
        ///        --sys.parameters parameter  on Pr.object_id = parameter.object_id
        ///        --inner join sys.types Type on parameter.system_type_id = Type.system_type_id
        ///        --where type = &apos;P&apos; 
        ///    [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string procs {
            get {
                return ResourceManager.GetString("procs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE FROM INFORMATION_SCHEMA.TABLES WHERE Table_name&lt;&gt;&apos;sysdiagrams&apos; and Table_Type=&apos;BASE TABLE&apos; and ISNULL(OBJECTPROPERTY(OBJECT_ID(TABLE_NAME), &apos;IsMSShipped&apos;), 0) = 0 ORDER BY TABLE_NAME 的本地化字符串。
        /// </summary>
        internal static string tables {
            get {
                return ResourceManager.GetString("tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --查询所有触发器
        ///select triggers.name as TriggerName,tables.name as TableName,triggers.is_disabled as Is_Disabled,
        ///triggers.is_instead_of_trigger AS Is_Instead_Of_Trigger,
        ///case when triggers.is_instead_of_trigger = 1 then &apos;INSTEAD OF&apos;
        ///     when triggers.is_instead_of_trigger = 0 then &apos;AFTER&apos;
        ///     else null
        ///end as Detail
        ///from sys.triggers triggers
        ///inner join sys.tables tables on triggers.parent_id = tables.object_id
        ///where triggers.type =&apos;TR&apos;
        ///order by triggers.create_date
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string triggers {
            get {
                return ResourceManager.GetString("triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --查询所有视图
        ///select views.Name as ViewName,Col.Name as ColName ,Type.name as TypeName,Col.max_length as Length
        ///        --,Col_Desc.Value as Col_Description
        ///from sys.views views
        ///inner join sys.columns Col on views.object_id  = Col.object_id
        ///inner join sys.types Type on Col.system_type_id = Type.system_type_id
        ///--left join sys.extended_properties Col_Desc 
        ///--    on Col_Desc.major_id=views.object_id and Col_Desc.minor_id=Col.Column_id and Col_Desc.class=1 
        ///order by Create_Date
        /// 的本地化字符串。
        /// </summary>
        internal static string viewcols {
            get {
                return ResourceManager.GetString("viewcols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE FROM INFORMATION_SCHEMA.TABLES WHERE Table_name&lt;&gt;&apos;sysdiagrams&apos; and Table_Type=&apos;VIEW&apos; and ISNULL(OBJECTPROPERTY(OBJECT_ID(TABLE_NAME), &apos;IsMSShipped&apos;), 0) = 0 ORDER BY TABLE_NAME 的本地化字符串。
        /// </summary>
        internal static string views {
            get {
                return ResourceManager.GetString("views", resourceCulture);
            }
        }
    }
}
