using System;
using System.Collections.Generic;
using System.Text;

namespace Common.Localizer
{
    public class XtraEditorsLocalizer_zhchs : DevExpress.XtraEditors.Controls.EditResLocalizer
    {
        public override string Language
        {
            get
            {
                return "简体中文";
            }
        }
        public override string GetLocalizedString(DevExpress.XtraEditors.Controls.StringId id)
        {
            switch (id)
            {
                case DevExpress.XtraEditors.Controls.StringId.None:
                    return "";
                case DevExpress.XtraEditors.Controls.StringId.CaptionError:
                    return "错误";
                case DevExpress.XtraEditors.Controls.StringId.InvalidValueText:
                    return "无效值";
                case DevExpress.XtraEditors.Controls.StringId.CheckChecked:
                    return "校验";
                case DevExpress.XtraEditors.Controls.StringId.CheckUnchecked:
                    return "非校验";
                case DevExpress.XtraEditors.Controls.StringId.CheckIndeterminate:
                    return "不确定";
                case DevExpress.XtraEditors.Controls.StringId.DateEditToday:
                    return "今天";
                case DevExpress.XtraEditors.Controls.StringId.DateEditClear:
                    return "清除";
                case DevExpress.XtraEditors.Controls.StringId.OK:
                    return "确定(&O)";
                case DevExpress.XtraEditors.Controls.StringId.Cancel:
                    return "取消";
                case DevExpress.XtraEditors.Controls.StringId.NavigatorFirstButtonHint:
                    return "第一个";
                case DevExpress.XtraEditors.Controls.StringId.NavigatorPreviousButtonHint:
                    return "前一个";
                case DevExpress.XtraEditors.Controls.StringId.NavigatorPreviousPageButtonHint:
                    return "前一页";
                case DevExpress.XtraEditors.Controls.StringId.NavigatorNextButtonHint:
                    return "下一个";
                case DevExpress.XtraEditors.Controls.StringId.NavigatorNextPageButtonHint:
                    return "下一页";
                case DevExpress.XtraEditors.Controls.StringId.NavigatorLastButtonHint:
                    return "最后一个";
                case DevExpress.XtraEditors.Controls.StringId.NavigatorAppendButtonHint:
                    return "追加";
                case DevExpress.XtraEditors.Controls.StringId.NavigatorRemoveButtonHint:
                    return "删除";
                case DevExpress.XtraEditors.Controls.StringId.NavigatorEditButtonHint:
                    return "编辑";
                case DevExpress.XtraEditors.Controls.StringId.NavigatorEndEditButtonHint:
                    return "结束编辑";
                case DevExpress.XtraEditors.Controls.StringId.NavigatorCancelEditButtonHint:
                    return "取消编辑";
                case DevExpress.XtraEditors.Controls.StringId.NavigatorTextStringFormat:
                    return "记录 {0} of {1}";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditMenuCut:
                    return "剪切";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditMenuCopy:
                    return "复制";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditMenuPaste:
                    return "粘贴";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditMenuDelete:
                    return "删除";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditMenuLoad:
                    return "调用";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditMenuSave:
                    return "保存";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditOpenFileFilter:
                    return ";*.ico;*.位图文件 (*.bmp)|*.bmp|GIF文件 (*.gif)|*.gif|JPEG文件 (*.jpg;*.jpeg)|*.jpg;*.jpeg|Icon 文件 (*.ico)|*.ico|所有图像文件 |*.bmp;*.gif;*.jpg;*.jpeg;*.ico;*.png;*.tif|所有文件 |*.*";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditSaveFileFilter:
                    return "位图文件 (*.bmp)|*.bmp|GIF文件 (*.gif)|*.gif|JPEG 文件 (*.jpg)|*.jpg";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditOpenFileTitle:
                    return "打开";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditSaveFileTitle:
                    return "另存为";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditOpenFileError:
                    return "错误的图像格式";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditOpenFileErrorCaption:
                    return "打开错误";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditCopyImageError:
                    return "不能拷贝图像";
                case DevExpress.XtraEditors.Controls.StringId.LookUpEditValueIsNull:
                    return "[编辑值为空]";
                case DevExpress.XtraEditors.Controls.StringId.LookUpInvalidEditValueType:
                    return "无效的 LookUpEdit 编辑值类型。";
                case DevExpress.XtraEditors.Controls.StringId.LookUpColumnDefaultName:
                    return "名称";
                case DevExpress.XtraEditors.Controls.StringId.MaskBoxValidateError:
                    return "输入值不完整,是否修正?\r\n\t\r\n\t\r\n\t是 - 返回编辑器,修正该值.\r\n\t否 -保留该值.\r\n\t取消 - 重设为原来的值.\r\n\t";
                case DevExpress.XtraEditors.Controls.StringId.UnknownPictureFormat:
                    return "未知的图形格式";
                case DevExpress.XtraEditors.Controls.StringId.DataEmpty:
                    return "没有图像数据";
                case DevExpress.XtraEditors.Controls.StringId.NotValidArrayLength:
                    return "无效的数组长度。";
                case DevExpress.XtraEditors.Controls.StringId.ImagePopupEmpty:
                    return "(空)";
                case DevExpress.XtraEditors.Controls.StringId.ImagePopupPicture:
                    return "(图像)";
                case DevExpress.XtraEditors.Controls.StringId.ColorTabCustom:
                    return "自定义";
                case DevExpress.XtraEditors.Controls.StringId.ColorTabWeb:
                    return "网页";
                case DevExpress.XtraEditors.Controls.StringId.ColorTabSystem:
                    return "系统";
                case DevExpress.XtraEditors.Controls.StringId.CalcButtonMC:
                    return "MC";
                case DevExpress.XtraEditors.Controls.StringId.CalcButtonMR:
                    return "MR";
                case DevExpress.XtraEditors.Controls.StringId.CalcButtonMS:
                    return "MS";
                case DevExpress.XtraEditors.Controls.StringId.CalcButtonMx:
                    return "M+";
                case DevExpress.XtraEditors.Controls.StringId.CalcButtonSqrt:
                    return "平方根";
                case DevExpress.XtraEditors.Controls.StringId.CalcButtonBack:
                    return "后退";
                case DevExpress.XtraEditors.Controls.StringId.CalcButtonCE:
                    return "CE";
                case DevExpress.XtraEditors.Controls.StringId.CalcButtonC:
                    return "C";
                case DevExpress.XtraEditors.Controls.StringId.CalcError:
                    return "计算错误";
                case DevExpress.XtraEditors.Controls.StringId.TabHeaderButtonPrev:
                    return "向左滚动";
                case DevExpress.XtraEditors.Controls.StringId.TabHeaderButtonNext:
                    return "向右滚动";
                case DevExpress.XtraEditors.Controls.StringId.TabHeaderButtonClose:
                    return "关闭";
                case DevExpress.XtraEditors.Controls.StringId.TabHeaderSelectorButton:
                    return "Show Window List";
                case DevExpress.XtraEditors.Controls.StringId.XtraMessageBoxOkButtonText:
                    return "确定(&O)";
                case DevExpress.XtraEditors.Controls.StringId.XtraMessageBoxCancelButtonText:
                    return "取消";
                case DevExpress.XtraEditors.Controls.StringId.XtraMessageBoxYesButtonText:
                    return "是(&Y)";
                case DevExpress.XtraEditors.Controls.StringId.XtraMessageBoxNoButtonText:
                    return "否(&N)";
                case DevExpress.XtraEditors.Controls.StringId.XtraMessageBoxAbortButtonText:
                    return "中断(&A)";
                case DevExpress.XtraEditors.Controls.StringId.XtraMessageBoxRetryButtonText:
                    return "重试(&R)";
                case DevExpress.XtraEditors.Controls.StringId.XtraMessageBoxIgnoreButtonText:
                    return "忽略(&I)";
                case DevExpress.XtraEditors.Controls.StringId.TextEditMenuUndo:
                    return "撤销(&U)";
                case DevExpress.XtraEditors.Controls.StringId.TextEditMenuCut:
                    return "剪切(&t)";
                case DevExpress.XtraEditors.Controls.StringId.TextEditMenuCopy:
                    return "复制(&C)";
                case DevExpress.XtraEditors.Controls.StringId.TextEditMenuPaste:
                    return "粘贴(&P)";
                case DevExpress.XtraEditors.Controls.StringId.TextEditMenuDelete:
                    return "删除(&D)";
                case DevExpress.XtraEditors.Controls.StringId.TextEditMenuSelectAll:
                    return "全选(&A)";
                case DevExpress.XtraEditors.Controls.StringId.FilterEditorTabText:
                    return "文本";
                case DevExpress.XtraEditors.Controls.StringId.FilterEditorTabVisual:
                    return "可视";
                case DevExpress.XtraEditors.Controls.StringId.FilterShowAll:
                    return "(全部显示)";
                case DevExpress.XtraEditors.Controls.StringId.FilterGroupAnd:
                    return "与";
                case DevExpress.XtraEditors.Controls.StringId.FilterGroupNotAnd:
                    return "非与";
                case DevExpress.XtraEditors.Controls.StringId.FilterGroupNotOr:
                    return "非或";
                case DevExpress.XtraEditors.Controls.StringId.FilterGroupOr:
                    return "或";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseAnyOf:
                    return "所有";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseBeginsWith:
                    return "以...开头";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseBetween:
                    return "在...之间";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseBetweenAnd:
                    return "在...与...之间";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseContains:
                    return "包含...";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseEndsWith:
                    return "以...结尾";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseEquals:
                    return "等于";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseGreater:
                    return "大于";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseGreaterOrEqual:
                    return "大于等于";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseIsNotNull:
                    return "不为空";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseIsNull:
                    return "为空";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseIsNotNullOrEmpty:
                    return "Is not blank";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseIsNullOrEmpty:
                    return "Is blank";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseLess:
                    return "小于";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseLessOrEqual:
                    return "小于等于";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseLike:
                    return "与...相符";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseNoneOf:
                    return "一个也没有";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseNotBetween:
                    return "不在...之间";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseDoesNotContain:
                    return "不包含";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseDoesNotEqual:
                    return "不等于";
                case DevExpress.XtraEditors.Controls.StringId.FilterClauseNotLike:
                    return "不相符";
                case DevExpress.XtraEditors.Controls.StringId.FilterEmptyEnter:
                    return "<输入值>";
                case DevExpress.XtraEditors.Controls.StringId.FilterEmptyParameter:
                    return "<输入参数>";
                case DevExpress.XtraEditors.Controls.StringId.FilterMenuAddNewParameter:
                    return "增加参数";
                case DevExpress.XtraEditors.Controls.StringId.FilterEmptyValue:
                    return "<空>";
                case DevExpress.XtraEditors.Controls.StringId.FilterMenuConditionAdd:
                    return "添加条件";
                case DevExpress.XtraEditors.Controls.StringId.FilterMenuGroupAdd:
                    return "添加组";
                case DevExpress.XtraEditors.Controls.StringId.FilterMenuClearAll:
                    return "清除所有";
                case DevExpress.XtraEditors.Controls.StringId.FilterMenuRowRemove:
                    return "删除组";
                case DevExpress.XtraEditors.Controls.StringId.FilterToolTipNodeAdd:
                    return "添加一个新的条件到组";
                case DevExpress.XtraEditors.Controls.StringId.FilterToolTipNodeRemove:
                    return "删除这个条件";
                case DevExpress.XtraEditors.Controls.StringId.FilterToolTipNodeAction:
                    return "操作";
                case DevExpress.XtraEditors.Controls.StringId.FilterToolTipValueType:
                    return "比较值(另一个字段值)";
                case DevExpress.XtraEditors.Controls.StringId.FilterToolTipElementAdd:
                    return "添加一个新的项目到列表";
                case DevExpress.XtraEditors.Controls.StringId.FilterToolTipKeysAdd:
                    return "(使用插入或新增键)";
                case DevExpress.XtraEditors.Controls.StringId.FilterToolTipKeysRemove:
                    return "(使用删除或削减键)";
                case DevExpress.XtraEditors.Controls.StringId.ContainerAccessibleEditName:
                    return "编辑控制";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringGroupOperatorAnd:
                    return "And";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringGroupOperatorOr:
                    return "Or";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringUnaryOperatorBitwiseNot:
                    return "~";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringUnaryOperatorIsNull:
                    return "Is Null";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringUnaryOperatorMinus:
                    return "-";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringUnaryOperatorNot:
                    return "Not";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringUnaryOperatorPlus:
                    return "+";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBinaryOperatorBitwiseAnd:
                    return "&";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBinaryOperatorBitwiseOr:
                    return "|";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBinaryOperatorBitwiseXor:
                    return "^";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBinaryOperatorDivide:
                    return "/";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBinaryOperatorEqual:
                    return "=";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBinaryOperatorGreater:
                    return ">";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBinaryOperatorGreaterOrEqual:
                    return ">=";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBinaryOperatorLess:
                    return "<";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBinaryOperatorLessOrEqual:
                    return "<=";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBinaryOperatorLike:
                    return "Like";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBinaryOperatorMinus:
                    return "-";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBinaryOperatorModulo:
                    return "%";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBinaryOperatorMultiply:
                    return "*";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBinaryOperatorNotEqual:
                    return "<>";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBinaryOperatorPlus:
                    return "+";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringBetween:
                    return "Between";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringIn:
                    return "In";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringIsNotNull:
                    return "Is Not Null";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringNotLike:
                    return "Not Like";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIif:
                    return "Iif";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsNull:
                    return "为空";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLen:
                    return "长度";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLower:
                    return "小写";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionNone:
                    return "无";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionSubstring:
                    return "切割字符串";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionTrim:
                    return "去空格";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionUpper:
                    return "大写";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsThisYear:
                    return "今天";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsThisMonth:
                    return "本月";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsThisWeek:
                    return "本周";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLocalDateTimeThisYear:
                    return "今年";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLocalDateTimeThisMonth:
                    return "本月";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLocalDateTimeLastWeek:
                    return "上周";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLocalDateTimeThisWeek:
                    return "本周";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLocalDateTimeYesterday:
                    return "昨天";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLocalDateTimeToday:
                    return "今天";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLocalDateTimeNow:
                    return "现在";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLocalDateTimeTomorrow:
                    return "明天";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLocalDateTimeDayAfterTomorrow:
                    return "后天";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLocalDateTimeNextWeek:
                    return "下周";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLocalDateTimeTwoWeeksAway:
                    return "两周";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLocalDateTimeNextMonth:
                    return "下个月";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLocalDateTimeNextYear:
                    return "明年";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsOutlookIntervalBeyondThisYear:
                    return "除了今年";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsOutlookIntervalLaterThisYear:
                    return "今年晚些时候";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsOutlookIntervalLaterThisMonth:
                    return "本月晚些时候";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsOutlookIntervalNextWeek:
                    return "下周";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsOutlookIntervalLaterThisWeek:
                    return "这周晚些时候";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsOutlookIntervalTomorrow:
                    return "明天";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsOutlookIntervalToday:
                    return "今天";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsOutlookIntervalYesterday:
                    return "昨天";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsOutlookIntervalEarlierThisWeek:
                    return "这周早些时候";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsOutlookIntervalLastWeek:
                    return "最后一周";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsOutlookIntervalEarlierThisMonth:
                    return "本月早些时候";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsOutlookIntervalEarlierThisYear:
                    return "今年早些时候";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsOutlookIntervalPriorThisYear:
                    return "在此之前一年";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionCustom:
                    return "自定义";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionCustomNonDeterministic:
                    return "常规不确定";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionIsNullOrEmpty:
                    return "空或空格";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionConcat:
                    return "串接";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionAscii:
                    return "Ascii";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionChar:
                    return "Char";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionToInt:
                    return "To int";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionToLong:
                    return "To long";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionToFloat:
                    return "To float";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionToDouble:
                    return "To double";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionToDecimal:
                    return "To decimal";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionToStr:
                    return "To str";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionReplace:
                    return "替换";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionReverse:
                    return "逆转";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionInsert:
                    return "插入";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionCharIndex:
                    return "字符索引";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionRemove:
                    return "移除";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionAbs:
                    return "Abs";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionSqr:
                    return "Sqr";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionCos:
                    return "Cos";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionSin:
                    return "Sin";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionAtn:
                    return "Atn";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionExp:
                    return "Exp";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLog:
                    return "Log";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionRnd:
                    return "Rnd";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionTan:
                    return "Tan";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionPower:
                    return "Power";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionSign:
                    return "Sign";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionRound:
                    return "Round";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionCeiling:
                    return "Ceiling";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionFloor:
                    return "Floor";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionMax:
                    return "Max";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionMin:
                    return "Min";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionAcos:
                    return "Acos";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionAsin:
                    return "Asin";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionAtn2:
                    return "Atn2";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionBigMul:
                    return "Big mul";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionCosh:
                    return "Cosh";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionLog10:
                    return "Log10";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionSinh:
                    return "Sinh";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionTanh:
                    return "Tanh";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionPadLeft:
                    return "左对齐";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionPadRight:
                    return "右对齐";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionDateDiffTick:
                    return "时间差（刻度）";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionDateDiffSecond:
                    return "时间差（秒）";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionDateDiffMilliSecond:
                    return "时间差（毫秒）";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionDateDiffMinute:
                    return "时间差（分钟）";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionDateDiffHour:
                    return "时间差（小时）";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionDateDiffDay:
                    return "时间差（天）";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionDateDiffMonth:
                    return "时间差（月）";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionDateDiffYear:
                    return "时间差（年）";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionGetDate:
                    return "获取日期";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionGetMilliSecond:
                    return "获取毫秒";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionGetSecond:
                    return "获取秒";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionGetMinute:
                    return "获取分钟";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionGetHour:
                    return "获取小时";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionGetDay:
                    return "获取天";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionGetMonth:
                    return "获取月";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionGetYear:
                    return "获取年";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionGetDayOfWeek:
                    return "获取星期几";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionGetDayOfYear:
                    return "获取一年中的天";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionGetTimeOfDay:
                    return "获取时间";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionNow:
                    return "获取现在时间";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionUtcNow:
                    return "获取现在时间（UTC）";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionToday:
                    return "获取今天的日期";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionAddTimeSpan:
                    return "增加时间跨度";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionAddTicks:
                    return "增加刻度";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionAddMilliSeconds:
                    return "增加毫秒";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionAddSeconds:
                    return "增加秒";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionAddMinutes:
                    return "增加分钟";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionAddHours:
                    return "增加小时";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionAddDays:
                    return "增加天数";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionAddMonths:
                    return "增加月数";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionAddYears:
                    return "增加年数";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionStartsWith:
                    return "从这里开始";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionEndsWith:
                    return "到这里结束";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaToStringFunctionContains:
                    return "包含";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaInvalidExpression:
                    return "指定的表达包含无效符号(第{0}行，第{1}列)";
                case DevExpress.XtraEditors.Controls.StringId.FilterCriteriaInvalidExpressionEx:
                    return "指定的表达式是无效的";
                case DevExpress.XtraEditors.Controls.StringId.Apply:
                    return "应用";
                case DevExpress.XtraEditors.Controls.StringId.PreviewPanelText:
                    return "预览:";
                case DevExpress.XtraEditors.Controls.StringId.TransparentBackColorNotSupported:
                    return "此控件不支持透明的背景色";
                case DevExpress.XtraEditors.Controls.StringId.FilterOutlookDateText:
                    return "查看全部|显示空值|过滤器的具体日期： |除了今年|今年晚些时候|本月晚些时候|下周|本星期晚些时候|明天|今天|昨天|本周|上周|本月|今年|在此之前一年";
                case DevExpress.XtraEditors.Controls.StringId.FilterDateTimeConstantMenuCaption:
                    return "日期常量";
                case DevExpress.XtraEditors.Controls.StringId.FilterDateTimeOperatorMenuCaption:
                    return "日期运算符";
                case DevExpress.XtraEditors.Controls.StringId.FilterDateTextAlt:
                    return "查看全部|显示空值|过滤器的具体日期：|较远的|下周|今天|本周|本月|最近的|{0:yyyy}, {0:MMMM}";
                case DevExpress.XtraEditors.Controls.StringId.FilterFunctionsMenuCaption:
                    return "Functions";
                case DevExpress.XtraEditors.Controls.StringId.DefaultBooleanTrue:
                    return "真";
                case DevExpress.XtraEditors.Controls.StringId.DefaultBooleanFalse:
                    return "假";
                case DevExpress.XtraEditors.Controls.StringId.DefaultBooleanDefault:
                    return "默认";
                case DevExpress.XtraEditors.Controls.StringId.ProgressExport:
                    return "导出";
                case DevExpress.XtraEditors.Controls.StringId.ProgressPrinting:
                    return "打印";
                case DevExpress.XtraEditors.Controls.StringId.ProgressCreateDocument:
                    return "创建文件";
                case DevExpress.XtraEditors.Controls.StringId.ProgressCancel:
                    return "取消";
                case DevExpress.XtraEditors.Controls.StringId.ProgressCancelPending:
                    return "取消等待";
                case DevExpress.XtraEditors.Controls.StringId.ProgressLoadingData:
                    return "加载数据";
                case DevExpress.XtraEditors.Controls.StringId.FilterAggregateAvg:
                    return "平均";
                case DevExpress.XtraEditors.Controls.StringId.FilterAggregateCount:
                    return "计数";
                case DevExpress.XtraEditors.Controls.StringId.FilterAggregateExists:
                    return "存在";
                case DevExpress.XtraEditors.Controls.StringId.FilterAggregateMax:
                    return "最大值";
                case DevExpress.XtraEditors.Controls.StringId.FilterAggregateMin:
                    return "最小值";
                case DevExpress.XtraEditors.Controls.StringId.FilterAggregateSum:
                    return "合计";
                case DevExpress.XtraEditors.Controls.StringId.FieldListName:
                    return "字段列表 ({0})";
                case DevExpress.XtraEditors.Controls.StringId.RestoreLayoutDialogFileFilter:
                    return "XML 文件 (*.xml)|*.xml|所有文件|*.*";
                case DevExpress.XtraEditors.Controls.StringId.SaveLayoutDialogFileFilter:
                    return "XML 文件 (*.xml)|*.xml";
                case DevExpress.XtraEditors.Controls.StringId.RestoreLayoutDialogTitle:
                    return "还原布局";
                case DevExpress.XtraEditors.Controls.StringId.SaveLayoutDialogTitle:
                    return "保存布局";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditMenuZoom:
                    return "缩放";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditMenuFullSize:
                    return "全屏";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditMenuFitImage:
                    return "图像填充";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditMenuZoomIn:
                    return "放大";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditMenuZoomOut:
                    return "缩小";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditMenuZoomTo:
                    return "放大到,";
                case DevExpress.XtraEditors.Controls.StringId.PictureEditMenuZoomToolTip:
                    return "{0}%";
            }
            return base.GetLocalizedString(id);
        }
    }
}
